name: Predict Gold Price

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 10 * * 1-5' # 10:30 UTC = 16:00 IST, Monday–Friday

jobs:
  build-and-predict:
    environment: development
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          node-version-file: '.nvmrc'
          cache: 'npm' # Cache node_modules

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test
        env:
          CI: true

      - name: Build Source Code
        run: npm run build

      - name: Run Price Prediction
        run: node dist/src/index.js
