name: Predict Gold Price - CI

on:
  workflow_dispatch: # To trigger the action from REST API
  pull_request:
    branches:
      - '**' # Runs on every branch

jobs:
  build-and-predict-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          node-version-file: '.nvmrc'
          cache: 'npm' # Cache node_modules

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test
        env:
          CI: true

      - name: Build Source Code
        run: npm run build

      - name: Run Price Prediction
        run: node dist/src/index.js
